---
- name: Workstation setup
  hosts: localhost
  become: true
  gather_facts: yes
  collections:
    - community.general

  # enable task debugging
  debugger: on_failed
  vars_prompt:
    - name: git_name
      prompt: "Please enter your git user.name"
      private: no
      default: "Anders Nyberg"

    - name: git_email
      prompt: "Please enter your git user.email"
      private: no
      default: "nypananders@gmail.com"

  vars:
    user: "{{ ansible_facts['env']['SUDO_USER'] }}" 
    home: "/home/{{ ansible_facts['env']['SUDO_USER'] }}"

  tasks:
    - name: Display stuff
      debug:
        msg: "OS user: >{{ user }}< ,home dir: >{{ home }}< , Git info {{ git_name }} , {{ git_email }}"
        
    - name: Perform a distribution upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_file

    - name: Reboot the server if required
      ansible.builtin.reboot:
      when: reboot_file.stat.exists

    - name: Remove unused dependencies
      ansible.builtin.apt:
        autoremove: yes

    - name: Update apt cache and install stow
      ansible.builtin.apt:
        name: stow
        state: present
        update_cache: yes


    - name: Install .config with stow
      ansible.builtin.shell:
        cmd: "stow . -t $TARGET -d $DEST"
      environment:
        TARGET: "{{home}}"
        DEST: "{{ playbook_dir }}/.."  # Go up one directory to dotfiles root
      
    - name: Install git 
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes

    - name: Display global gitconfig 
      community.general.git_config_info: 
        scope: file
        path: "{{home}}/.gitconfig"
      register: result_config

    - name: Dump git config 
      ansible.builtin.debug:
        msg: "{{ result_config | default('(not set)', true) }}"

    - name: Add alias st setting to ~/.gitconfig
      community.general.git_config:
        name: alias.st
        scope: file
        file: "{{home}}/.gitconfig"
        value: status

    - name: Add email to gitconfig
      community.general.git_config:     
        name: user.email
        scope: file
        file: "{{home}}/.gitconfig"
        value: "{{git_email}}"

    - name: Add name to gitconfig 
      community.general.git_config:
        name: user.name
        scope: file
        file: "{{home}}/.gitconfig"
        value: "{{git_name}}"

    - name: Install essential packages
      ansible.builtin.apt:
        name:
          - htop
          - unzip
          - wget
          - jq
          - bat
          - xclip
          - curl
          - ffmpeg
          - fd-find
          - tree
          - ripgrep
        state: present
        update_cache: yes

    - name: Download Neovim AppImage
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/download/v0.12.2/nvim-linux-x86_64.appimage 
        dest: /usr/local/bin/nvim
        mode: '0755'

    - name: Create a symlink for nvim (Optional)
      ansible.builtin.file:
        src: /usr/local/bin/nvim
        dest: /usr/bin/nvim
        state: link


    - name: Install zsh
      ansible.builtin.package:
        name: zsh
        state: present
      become: true

    - name: Set user shell to zsh
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/zsh
      become: true

    - name: Download ohmyzsh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "/home/{{ user }}/install.sh"
        mode: '0755'

    - name: Install ohmyzsh
      ansible.builtin.script:
        cmd: "/home/{{ user }}/install.sh"

    - name: Install PowerLevel10K
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "/home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1

    - name: Download NerdFonts
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Meslo.zip
        dest: "/home/{{ user }}/Meslo.zip"

    - name: Create temp directory
      ansible.builtin.file:
        path: "/home/{{ user }}/Meslo"
        state: directory
        mode: '0755'

    - name: Install font files
      ansible.builtin.unarchive:
        src: "/home/{{ user }}/Meslo.zip"
        dest: "/home/{{ user }}/Meslo"

    - name: Move font files to fonts directory
      ansible.builtin.copy:
        src: "/home/{{ user }}/Meslo"
        dest: /usr/share/fonts/Meslo
        owner: root
      become: true

    - name: Update .zshrc
      ansible.builtin.lineinfile:
        path: "/home/{{ user }}/.zshrc"
        insertafter: EOF
        line: "source /home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme"
        
